// Generated by CoffeeScript 1.4.0
(function() {
  var AdminApp;

  yepnope({
    load: ['lib/jquery-1.8.2.min.js', 'bs/css/bootstrap.min.css', 'bs/js/bootstrap.min.js', 'lib/custom-web/date.js', 'lib/custom-web/cross-utils.js', 'lib/common-web/underscore-min.js', 'lib/common-web/underscore.strings.js', 'css/admin.css', 'lib/lima1/net.js'],
    complete: function() {
      return $(document).ready(function() {
        var app;
        log('App started');
        app = new AdminApp;
        return app.start();
      });
    }
  });

  AdminApp = (function() {

    AdminApp.prototype.SAVED_TOKEN = 'token';

    function AdminApp() {
      var jqnet,
        _this = this;
      jqnet = new jQueryTransport('https://lima1-kvj.rhcloud.com');
      this.oauth = new OAuthProvider({
        clientID: 'lima1admin',
        scope: 'web'
      }, jqnet);
      this.oauth.on_token_error = function() {
        return _this.login();
      };
    }

    AdminApp.prototype.start = function() {
      var token;
      token = typeof window !== "undefined" && window !== null ? window.localStorage[this.SAVED_TOKEN] : void 0;
      if (token) {
        this.oauth.token = token;
        return this.loadUserInfo();
      } else {
        return this.login();
      }
    };

    AdminApp.prototype.loadUserInfo = function() {
      var _this = this;
      return this.oauth.rest('', '/rest/admin/users/info?', null, function(err, data) {
        if (err) {
          return _this.showError(err);
        }
        return log('UserInfo:', data);
      });
    };

    AdminApp.prototype.login = function() {
      var dialog, password, remember, username,
        _this = this;
      dialog = $('#main-login-dialog');
      username = dialog.find('#login-username');
      password = dialog.find('#login-password');
      remember = dialog.find('#login-remember');
      password.val('');
      dialog.modal('show');
      username.focus();
      return dialog.find('#login-do-login').unbind('click').bind('click', function(e) {
        return _this.oauth.tokenByUsernamePassword(username.val(), password.val(), function(err, data) {
          var _ref;
          if (err) {
            _this.showError((_ref = err.error_description) != null ? _ref : err);
            password.val('');
            username.focus();
            return;
          }
          if (typeof window !== "undefined" && window !== null) {
            delete window.localStorage[_this.SAVED_TOKEN];
          }
          if (remember.attr('checked')) {
            if (typeof window !== "undefined" && window !== null) {
              window.localStorage[_this.SAVED_TOKEN] = data.access_token;
            }
          }
          log('Token', data, remember.attr('checked'));
          dialog.modal('hide');
          return _this.loadUserInfo();
        });
      });
    };

    AdminApp.prototype.showError = function(message) {
      return this.showAlert(message, {
        severity: 'error'
      }, 'Error');
    };

    AdminApp.prototype.showPrompt = function(message, handler) {
      var alert, button, div,
        _this = this;
      div = $(document.createElement('p'));
      button = $(document.createElement('button')).addClass('btn btn-danger').text('Proceed').appendTo(div);
      button.bind('click', function(e) {
        if (handler) {
          handler();
        }
        return alert.remove();
      });
      return alert = this.showAlert(message, {
        persistent: true,
        severity: 'block',
        content: div
      }, 'Prompt');
    };

    AdminApp.prototype.showAlert = function(message, config, title) {
      var div, _ref, _ref1,
        _this = this;
      if (title == null) {
        title = 'Whiskey2';
      }
      div = $(document.createElement('div')).appendTo($('#alerts')).addClass('alert alert-' + ((_ref = config != null ? config.severity : void 0) != null ? _ref : 'info'));
      $(document.createElement('button')).appendTo(div).addClass('close').attr({
        'data-dismiss': 'alert'
      }).html('&times;');
      $(document.createElement('h4')).appendTo(div).text(title != null ? title : 'Untitled');
      $(document.createElement('span')).appendTo(div).text(message);
      if (config != null ? config.content : void 0) {
        div.append(config.content);
      }
      if (!(config != null ? config.persistent : void 0)) {
        setTimeout(function() {
          return div.remove();
        }, (_ref1 = config != null ? config.timeout : void 0) != null ? _ref1 : 3000);
      }
      return div;
    };

    return AdminApp;

  })();

}).call(this);
